spring:
  application:
    name: eureka-service

server:
  port: 8302
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
      wait-time-in-ms-when-sync-empty: 10000
  instance:
    hostname: localhost

zuul:
  #service will be mapped under /api URI
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8300
    stock-service:
      path: /stock-service/**
      url: http://localhost:8301